[package]
name = "message"
version = "0.1.0"
edition = "2021"

[dependencies]
postcard = { version = "1.1.3", default-features = false }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
